services:
  - type: worker
    name: Web-Screenshot-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python __main__.py
    repo: https://github.com/sholoomail/Web-Screenshot-Bot.git
    branch: master
    envVars:
      - key: TOKEN 
        sync: false
      - key: CHROMEDRIVER_PATH 
        value: /app/.chromedriver/bin/chromedriver
      - key: LD_LIBRARY_PATH 
        value: /app/.heroku/vendor/lib:/app/.heroku/python/lib:/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/usr/lib/i386-linux-gnu:/app/.apt/usr/lib:
      - key: GOOGLE_CHROME_BIN 
        value: /app/.apt/usr/bin/google-chrome
      - key: PYTHON_VERSION 
        value: 3.9.0
